### PR TITLE
Support link dropEffect

### PR DESCRIPTION
**Pull request by nantunes**
`determineEffectAllowed` chooses `link` type if `metaKey` is pressed.
It also have fallbacks in case the computed effect isn't allowed by `e.dataTransfer.effectAllowed`.

`e.dataTransfer.effectAllowed` can be overridden by `attrs.effectAllowed`, defaulting to `'copyMove'` as before.

### CODE REVIEW

**Comment by ganarajpr** [comment]
Hi, 
Thank you for the PR. Could you please update the documentation with the new options you have added? The more information ( examples perhaps with plunker? )  the documentation has, the better it is for people to use the feature you have added.

**Comment by nantunes** [comment]
Hi @ganarajpr 
Will update the PR soon. Thanks.

**Comment by nantunes** [comment]
I'm having some difficulty with browser inconsistencies:
- In Chrome (desktop, mac), all ok, except when `effect-allowed="all"`: in that case it shows the _copy_ cursor by default, doesn't allow moves (it's ok with links holding ctrl), but provides the value of `dataTransfer.dropEffect` as `copy` to the drop source and as `move` to the drop target.
- In Safari (desktop, mac) `effectAllowed` is ignored on the drop target and always return `all`.

See plunk: http://plnkr.co/edit/VBy0wwVY45uBLW7zOMLx?p=preview

Didn't test other browsers, either desktop or mobile.
I will not be able to advance further at least until the end of next week.

**Comment by ganarajpr** [comment]
I am closing this PR. If you make any progress - let me know and we can do with a fresh PR.

**Pull request closed without merging**
