### PR TITLE
Fix calling function on drop failure.

### PR DESCRIPTION
**Pull request by iradovanovic**

### CODE REVIEW

**Comment by iradovanovic** [comment]
Sure. WIll be done during the day.

**Comment by iradovanovic** [comment]
Ah, I took a look on documentation. In the documentation is perfectly explained how should work/use it, just was a bug in your code. This on-drop-failure was never executed.

**Comment by ganarajpr** [comment]
Ty. Just noticed this as well.

**Comment by iradovanovic** [comment]
:+1: 
Ty for accepting.

**Comment by iradovanovic** [comment]
Version number?

**Pull request merged**
